
route:
  receiver: 'webhook'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30s
  group_by: [cluster, alertname]

receivers:
    - name: 'webhook'
      webhook_configs:
        - url: 'http://eda:5001/alertmanager'
